# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32821bdf789653d528d67da70776629d45c9a368ba73ea7a7ddd44d0e166c89d8100919bd9353d4bd9a1c85adebf69af98481398a471c795152ab4a872b133e5

test:
  secret_key_base: 0dc525687562cf982f88e54da084032dec3235e52c4f2bcb22388f51dd4cabb1414853a7bc26f935de65ed21ae11f5363c9e2aa52ccf4c892da992595b80d230

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
